name: Notify Microsoft 365

on: [push] # 이벤트를 변경하여 다른 GitHub 이벤트에 대응하게 할 수 있습니다.

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Microsoft 365
        run: |
          curl -H 'Content-Type: application/json' -d '{"text": "새로운 커밋이 발생했습니다! ${{ github.actor }}"}' ${{secrets.M365_WEBHOOK_URL}}
